NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
source("Plot1.R")
source("Plot2.R")
source("Plot3.R")
source("Plot4.R")
source("Plot5.R")
source("Plot6.R")
